name: CI

on:
  push:
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
  pull_request:
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Makefile
        run: |
          echo "LDFLAGS=-lm -fsanitize=address" > config.mk
      - name: Build
        run: make
      - name: Run
        run: chmod +x mdp && ./mdp
